browser=edge
baseUrl=https://www.saucedemo.com
implicitWait=10

# Page URLs
productsUrl=/inventory.html
productDetailUrl=/inventory-item.html
cartUrl=/cart.html
checkoutStep1Url=/checkout-step-one.html
checkoutStep2Url=/checkout-step-two.html
checkoutCompleteUrl=/checkout-complete.html
